apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.issuerConfig.cloudflare.issuerName }}
spec:
  acme:
    email: {{ .Values.issuerConfig.email }}
    server: {{ .Values.issuerConfig.acmeServer }}
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: {{ .Values.issuerConfig.cloudflare.secretName }}
            key: {{ .Values.issuerConfig.cloudflare.secretKey }}