apiVersion: v1
kind: Namespace
metadata:
  name: helloworld
  labels:
    app.kubernetes.io/managed-by: argocd
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: helloworld-quota
  namespace: helloworld
spec:
  hard:
    limits.cpu: "300m"
    limits.memory: "300Mi"