apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - metallb-ns.yaml
  - helloworld-ns.yaml
  - pihole-ns.yaml
  - wg-easy-ns.yaml
  - cloudflare-ddns-ns.yaml
  - cert-manager-ns.yaml