apiVersion: v1
kind: Namespace
metadata:
  name: pihole
  labels:
    app.kubernetes.io/managed-by: argocd
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: pihole-quota
  namespace: pihole
spec:
  hard:
    limits.cpu: "500m"
    limits.memory: "2Gi"