apiVersion: v1
kind: Namespace
metadata:
  name: wg-easy
  labels:
    app.kubernetes.io/managed-by: argocd
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: wg-easy-quota
  namespace: wg-easy
spec:
  hard:
    limits.cpu: "500m"
    limits.memory: "1Gi"