apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system
helmCharts:
- name: metallb
  releaseName: metallb
  version: 0.16.1
  repo: https://metallb.github.io/metallb
  # valuesFile: values.yaml
resources:
- crds.yaml