apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - projects/default.yaml
  - applications/namespaces.yaml
  - applications/metallb.yaml
  - applications/argocd.yaml
  - applications/helloworld.yaml
  - applications/pihole.yaml
  - applications/wg-easy.yaml
  - applications/traefik.yaml