apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/sylvan-c/home-lab-gitops.git'
    targetRevision: main
    path: install-manifests/metallb
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true