apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: 'https://github.com/sylvan-c/home-lab-gitops.git'
    targetRevision: main
    path: apps/metallb
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true