apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/sylvan-c/home-lab-gitops.git'
    targetRevision: main
    path: apps/traefik
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true