email: "sylvanchouhan@gmail.com"

acmeServer: "https://acme-v02.api.letsencrypt.org/directory"

cloudflare:
  secretKey: "api-token"
  secretName: "cloudflare-api-secret"
  issuerName: "letsencrypt-dns01"