apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: static-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.201-192.168.1.210
  autoAssign: false
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: dynamic-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.211-192.168.1.250
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advert
  namespace: metallb-system
spec:
  ipAddressPools:
  - dynamic-pool
  - static-pool